import { unstable_cache } from "next/cache";
import { createClient, createPublicClient } from "@/lib/supabase/server";
import type { Locale } from "@/i18n/config";
export { local, type ClickBehavior, type SiteItem } from "@/lib/cms-shared";
import type { SiteItem } from "@/lib/cms-shared";
export type Section={id:string;key:string;page_key:string;section_type:string;title_he:string|null;title_ar:string|null;subtitle_he:string|null;subtitle_ar:string|null;settings:Record<string,string>;is_visible:boolean;sort_order:number};
const itemFields="id,section_id,parent_id,item_type,title_he,title_ar,description_he,description_ar,show_button,click_behavior,cta_label_he,cta_label_ar,cta_href,image_url,file_url,media_title_he,media_title_ar,media_size,media_fit,media_position,original_file_name,media_mime_type,icon_key,variant,is_visible,sort_order,settings";
async function fetchPublishedPageCms(pageKey:string){const supabase=createPublicClient();const {data:sections}=await supabase.from("site_sections").select("id,key,page_key,section_type,title_he,title_ar,subtitle_he,subtitle_ar,settings,is_visible,sort_order").eq("page_key",pageKey).eq("status","published").eq("is_visible",true).is("deleted_at",null).order("sort_order");const ids=(sections??[]).map(s=>s.id);if(!ids.length)return {sections:[] as Section[],items:[] as SiteItem[]};const {data:items}=await supabase.from("site_items").select(itemFields).in("section_id",ids).eq("status","published").eq("is_visible",true).is("deleted_at",null).order("sort_order");return {sections:(sections??[]) as Section[],items:(items??[]) as SiteItem[]};}
const cachedPageCms=(pageKey:string)=>unstable_cache(()=>fetchPublishedPageCms(pageKey),["cms-page",pageKey],{revalidate:300,tags:["cms",`cms:${pageKey}`]})();
async function fetchAdminPageCms(pageKey:string){const supabase=await createClient();const {data:sections}=await supabase.from("site_sections").select("id,key,page_key,section_type,title_he,title_ar,subtitle_he,subtitle_ar,settings,is_visible,sort_order").eq("page_key",pageKey).is("deleted_at",null).order("sort_order");const ids=(sections??[]).map(s=>s.id);if(!ids.length)return {sections:[] as Section[],items:[] as SiteItem[]};const {data:items}=await supabase.from("site_items").select(itemFields).in("section_id",ids).is("deleted_at",null).order("sort_order");return {sections:(sections??[]) as Section[],items:(items??[]) as SiteItem[]};}
export async function getPageCms(pageKey:string,includeDraft=false){return includeDraft?fetchAdminPageCms(pageKey):cachedPageCms(pageKey)};
const cachedTheme=unstable_cache(async()=>{const supabase=createPublicClient();const {data}=await supabase.from("theme_settings").select("theme_key").eq("is_active",true).maybeSingle();return data?.theme_key||"original";},["active-theme"],{revalidate:300,tags:["theme"]});
export async function getActiveTheme(){return cachedTheme();}
