import Link from "next/link";
import { ArrowLeft, BookOpen, BrainCircuit, Pencil } from "lucide-react";
import type { Locale } from "@/i18n/config";
import { t } from "@/i18n/dictionaries";
import { getPageCms, local } from "@/lib/cms";
import { InlineSectionEditor } from "@/components/cms/InlineSectionEditor";
import { AddItemCard, InlineItemEditor } from "@/components/cms/InlineItemEditor";
import { CardMedia } from "@/components/cms/CardMedia";
import { CardButton } from "@/components/cms/CardButton";
import { GridSettings } from "@/components/cms/GridSettings";
const icons={pencil:Pencil,book:BookOpen,brain:BrainCircuit,leaf:BookOpen,star:BookOpen,download:BookOpen};
const columns=(settings:Record<string,unknown>)=>Math.min(4,Math.max(1,Number(settings.columns)||3));
export async function LocalizedHome({locale,isAdmin=false}:{locale:Locale;isAdmin?:boolean}) { const d=t(locale); const {sections,items}=await getPageCms("home",isAdmin); const byKey=(key:string)=>sections.find(s=>s.key===key); const hero=byKey("home.hero"),features=byKey("home.features"),explore=byKey("home.explore"); const heroTitle=hero?local(hero,"title",locale):d.home.title; const heroSubtitle=hero?local(hero,"subtitle",locale):d.home.description; const featureItems=features?items.filter(i=>i.section_id===features.id):[]; return <><section className="hero cms-section">{hero&&<InlineSectionEditor locale={locale} section={hero}/>}<div className="container hero-grid"><div className="hero-copy"><span className="eyebrow">{d.home.eyebrow}</span><h1>{heroTitle}</h1><p>{heroSubtitle}</p><Link className="button" href={String(hero?.settings.cta_href||"#guide")}>{String(hero?.settings[`cta_label_${locale}`]||d.home.start)}<ArrowLeft size={18}/></Link></div><div className="hero-art" aria-hidden="true"><i className="branch a">❧</i><i className="branch b">❧</i><div className="paper paper-one"><span className="arabic">ب</span></div><div className="paper paper-two"><span className="arabic">ع</span></div><div className="paper paper-three"><span className="arabic">ح</span></div><div className="pencil"/></div></div></section>{features&&<section id="guide" className="feature-section container cms-section"><InlineSectionEditor locale={locale} section={features}/><GridSettings locale={locale} section={features}/><div className="feature-grid cms-card-grid" style={{"--desktop-columns":columns(features.settings)} as React.CSSProperties}>{featureItems.map(item=>{const Icon=icons[item.icon_key as keyof typeof icons]||BookOpen;return <article key={item.id} className={`feature-card cms-editable-card ${item.variant||""}`}><InlineItemEditor locale={locale} item={item}/><CardMedia item={item} locale={locale} position="top"/><span className="feature-icon"><Icon size={27}/></span><h2>{local(item,"title",locale)}</h2><p>{local(item,"description",locale)}</p><CardButton item={item} locale={locale}/><CardMedia item={item} locale={locale} position="bottom"/></article>})}<AddItemCard locale={locale} sectionId={features.id} label={locale==="he"?"הוסף כרטיס":"إضافة بطاقة"}/></div></section>}<section className="explore container cms-section">{explore&&<InlineSectionEditor locale={locale} section={explore}/>}<div className="section-intro"><span className="eyebrow">{d.home.guide}</span><h2>{explore?local(explore,"title",locale):d.home.threeWays}</h2><p>{explore?local(explore,"subtitle",locale):d.home.threeDesc}</p></div></section></>; }
