"use client";
import Link from "next/link";
import { Menu, X } from "lucide-react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import type { Locale } from "@/i18n/config";
import { t } from "@/i18n/dictionaries";
import { createClient } from "@/lib/supabase/client";

export function Brand({locale}:{locale:Locale}) { const d=t(locale); return <Link href={`/${locale}`} className="brand" aria-label={d.brand}><span className="leaf" aria-hidden="true">❧</span><span>{locale === "he" ? <>קדם־כתיבה<br/><b>בערבית</b></> : <>الكتابة التمهيدية<br/><b>بالعربية</b></>}</span></Link>; }
function Avatar({user}:{user:User}) { const name=(user.user_metadata.full_name || user.user_metadata.name || user.email || "?") as string; const photo=user.user_metadata.avatar_url || user.user_metadata.picture; return photo ? <img className="user-avatar" src={photo} alt="" referrerPolicy="no-referrer"/> : <span className="avatar-fallback">{name.split(" ").slice(0,2).map((x:string)=>x[0]).join("")}</span>; }
export function Header({locale}:{locale:Locale}) { const d=t(locale); const path=usePathname(); const router=useRouter(); const [open,setOpen]=useState(false); const [user,setUser]=useState<User|null>(null); const [admin,setAdmin]=useState(false); const [drop,setDrop]=useState(false);
  useEffect(()=>{ const supabase=createClient(); supabase.auth.getUser().then(async ({data})=>{ setUser(data.user); if(data.user) { const {data:row}=await supabase.from("admins").select("user_id").eq("user_id",data.user.id).maybeSingle(); setAdmin(!!row); } }); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null)); return ()=>subscription.unsubscribe(); },[]);
  const switchTo=(to:Locale)=>{ const parts=path.split("/"); parts[1]=to; router.push(parts.join("/") || `/${to}`); };
  const links=["home","letters","worksheets","resources","weeklyTip","project","about"] as const; const hrefs=["","letters","worksheets","resources","weekly-tip","project","about"];
  const signOut=async()=>{ await createClient().auth.signOut(); setDrop(false); router.refresh(); };
  return <header className="header"><div className="nav-wrap"><Brand locale={locale}/><nav className="desktop-nav" aria-label="navigation">{links.map((key,i)=><Link key={key} href={`/${locale}/${hrefs[i]}`}>{d.nav[key]}</Link>)}</nav><div className="nav-actions"><div className="language-switch"><button className={locale==="he"?"active":""} onClick={()=>switchTo("he")}>עברית</button><span>|</span><button className={locale==="ar"?"active":""} onClick={()=>switchTo("ar")}>العربية</button></div>{user?<div className="user-menu"><button className="user-control" onClick={()=>setDrop(!drop)}><Avatar user={user}/><span>{user.user_metadata.full_name||user.user_metadata.name||user.email}</span></button>{drop&&<div className="user-dropdown"><b>{user.user_metadata.full_name||user.user_metadata.name}</b><small>{user.email}</small>{admin&&<Link href={`/${locale}/admin`} onClick={()=>setDrop(false)}>{d.nav.admin}</Link>}<button onClick={signOut}>{d.auth.logout}</button></div>}</div>:<Link className="login-link" href={`/${locale}/login`}>{d.auth.login}</Link>}<button className="icon-button menu" aria-label="menu" aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="mobile-nav" aria-label="navigation">{links.map((key,i)=><Link key={key} href={`/${locale}/${hrefs[i]}`} onClick={()=>setOpen(false)}>{d.nav[key]}</Link>)}<div className="language-switch"><button onClick={()=>switchTo("he")}>עברית</button><span>|</span><button onClick={()=>switchTo("ar")}>العربية</button></div>{admin&&<Link href={`/${locale}/admin`}>{d.nav.admin}</Link>}</nav>}</header>; }
