"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireAdmin } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
const slugify=(v:string)=>v.trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const value=(fd:FormData,key:string)=>String(fd.get(key)||"").trim();
export async function signOut(locale:string) { const supabase=await createClient(); await supabase.auth.signOut(); redirect(`/${locale}`); }
export async function saveCategory(locale:string, formData:FormData) { const user=await requireAdmin(locale); const supabase=await createClient(); const id=value(formData,"id"); const data={name_he:value(formData,"name_he"),name_ar:value(formData,"name_ar")||null,description_he:value(formData,"description_he")||null,description_ar:value(formData,"description_ar")||null,slug:slugify(value(formData,"slug")||value(formData,"name_he")),sort_order:Number(value(formData,"sort_order")||0),is_visible:formData.get("is_visible")==="on",updated_by:user.id}; if(!data.name_he||!data.slug) throw new Error("Category name and slug are required"); const result=id?await supabase.from("categories").update(data).eq("id",id):await supabase.from("categories").insert({...data,created_by:user.id}); if(result.error) throw new Error(result.error.message); revalidatePath(`/${locale}/admin/categories`); }
export async function deleteCategory(locale:string, formData:FormData) { await requireAdmin(locale); const id=value(formData,"id"); const supabase=await createClient(); const {count}=await supabase.from("content_items").select("id",{count:"exact",head:true}).eq("category_id",id); if(count) throw new Error("Move or delete associated content before deleting this category."); const {error}=await supabase.from("categories").delete().eq("id",id); if(error) throw new Error(error.message); revalidatePath(`/${locale}/admin/categories`); }
export async function saveContent(locale:string, formData:FormData) { const user=await requireAdmin(locale); const supabase=await createClient(); const id=value(formData,"id"); const status=value(formData,"status")==="published"?"published":"draft"; const data={category_id:value(formData,"category_id")||null,title_he:value(formData,"title_he"),title_ar:value(formData,"title_ar")||null,excerpt_he:value(formData,"excerpt_he")||null,excerpt_ar:value(formData,"excerpt_ar")||null,body_he:value(formData,"body_he")||null,body_ar:value(formData,"body_ar")||null,cover_image_url:value(formData,"cover_image_url")||null,slug:slugify(value(formData,"slug")||value(formData,"title_he")),status,sort_order:Number(value(formData,"sort_order")||0),published_at:status==="published"?new Date().toISOString():null,updated_by:user.id}; if(!data.title_he||!data.slug) throw new Error("Hebrew title and slug are required"); const result=id?await supabase.from("content_items").update(data).eq("id",id):await supabase.from("content_items").insert({...data,created_by:user.id}); if(result.error) throw new Error(result.error.message); revalidatePath(`/${locale}/admin/content`); }
export async function deleteContent(locale:string, formData:FormData) { await requireAdmin(locale); const supabase=await createClient(); const {error}=await supabase.from("content_items").delete().eq("id",value(formData,"id")); if(error) throw new Error(error.message); revalidatePath(`/${locale}/admin/content`); }
export async function addAdmin(locale:string, formData:FormData) { const user=await requireAdmin(locale); const email=value(formData,"email").toLowerCase(); const supabase=await createClient(); const {data:profile,error}=await supabase.from("profiles").select("id").eq("email",email).maybeSingle(); if(error) throw new Error(error.message); if(!profile) throw new Error("This person must sign in once before receiving administrator access."); const {error:insertError}=await supabase.from("admins").insert({user_id:profile.id,created_by:user.id}); if(insertError) throw new Error(insertError.code==="23505"?"This user is already an administrator.":insertError.message); revalidatePath(`/${locale}/admin/admins`); }
export async function removeAdmin(locale:string, formData:FormData) { await requireAdmin(locale); const id=value(formData,"id"); const supabase=await createClient(); const {count}=await supabase.from("admins").select("user_id",{count:"exact",head:true}); if((count||0)<=1) throw new Error("The final administrator cannot be removed."); const {error}=await supabase.from("admins").delete().eq("user_id",id); if(error) throw new Error(error.message); revalidatePath(`/${locale}/admin/admins`); }
export async function deleteMedia(locale:string, formData:FormData) { await requireAdmin(locale); const id=value(formData,"id"),path=value(formData,"path"); const supabase=await createClient(); const {data:items}=await supabase.from("content_items").select("id").eq("cover_image_url",path); if(items?.length) throw new Error("This file is used as a content cover. Change the reference before deletion."); const {error}=await supabase.storage.from("site-media").remove([path]); if(error) throw new Error(error.message); await supabase.from("media").delete().eq("id",id); revalidatePath(`/${locale}/admin/media`); }
