-- Arabic Writing Foundations: consolidated initial schema.
-- Intended for a fresh Supabase project/reset only. Do not apply alongside the old split migrations.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;

create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade, email text not null, full_name text, avatar_url text,
 preferred_locale text not null default 'he' check (preferred_locale in ('he','ar')), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.admins (user_id uuid primary key references auth.users(id) on delete cascade,created_at timestamptz not null default now(),created_by uuid references auth.users(id));
create or replace function public.is_admin(check_user uuid default auth.uid()) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.admins where user_id=check_user);$$;
revoke all on function public.is_admin(uuid) from public; grant execute on function public.is_admin(uuid) to anon,authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name,avatar_url) values(new.id,coalesce(new.email,''),coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name'),coalesce(new.raw_user_meta_data->>'avatar_url',new.raw_user_meta_data->>'picture')) on conflict(id) do update set email=excluded.email,full_name=coalesce(excluded.full_name,profiles.full_name),avatar_url=coalesce(excluded.avatar_url,profiles.avatar_url),updated_at=now(); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table public.categories (
 id uuid primary key default gen_random_uuid(),name_he text not null,name_ar text,description_he text,description_ar text,slug text unique not null check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),icon text,color text,design_variant text,image_url text,alt_he text,alt_ar text,sort_order integer not null default 0,is_visible boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id)
);
create table public.content_items (
 id uuid primary key default gen_random_uuid(),category_id uuid references public.categories(id) on delete restrict,title_he text not null,title_ar text,slug text unique not null check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),excerpt_he text,excerpt_ar text,body_he text,body_ar text,cover_image_url text,status text not null default 'draft' check(status in ('draft','published')),sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),published_at timestamptz,created_by uuid references auth.users(id),updated_by uuid references auth.users(id)
);
create table public.media (
 id uuid primary key default gen_random_uuid(),storage_path text unique not null,file_name text not null,mime_type text not null,size_bytes bigint not null check(size_bytes>=0),alt_he text,alt_ar text,focal_position text check(focal_position in ('center','top','bottom') or focal_position is null),uploaded_by uuid references auth.users(id),created_at timestamptz not null default now()
);
create table public.site_sections (
 id uuid primary key default gen_random_uuid(),key text unique not null check(key~'^[a-z0-9._-]+$'),page_key text not null check(page_key in ('home','letters','worksheets','resources','weekly-tip','project','about','skills','strategies')),section_type text not null check(section_type in ('hero','feature_grid','explore','content','author','footer','header','tip')),title_he text,title_ar text,subtitle_he text,subtitle_ar text,status text not null default 'published' check(status in ('draft','published')),is_visible boolean not null default true,sort_order integer not null default 0,settings jsonb not null default '{}'::jsonb,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id)
);
create table public.site_items (
 id uuid primary key default gen_random_uuid(),section_id uuid not null references public.site_sections(id) on delete restrict,item_type text not null check(item_type in ('text','feature_card','image','resource_card','download','callout','quote','button','letter_group','tip','nav_link')),title_he text,title_ar text,description_he text,description_ar text,cta_label_he text,cta_label_ar text,cta_href text check(cta_href is null or cta_href~'^(\/(he|ar))?\/?[A-Za-z0-9_./#?=&%-]*$'),image_url text,file_url text,alt_he text,alt_ar text,media_title_he text,media_title_ar text,media_size text not null default 'medium' check(media_size in ('small','medium','large')),media_fit text not null default 'cover' check(media_fit in ('cover','contain')),media_position text not null default 'top' check(media_position in ('top','bottom')),original_file_name text,media_mime_type text,icon_key text check(icon_key is null or icon_key in ('pencil','book','brain','leaf','star','download')),variant text check(variant is null or variant in ('sage','peach','lavender','yellow','default','minimal')),status text not null default 'published' check(status in ('draft','published')),is_visible boolean not null default true,sort_order integer not null default 0,settings jsonb not null default '{}'::jsonb,deleted_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),created_by uuid references auth.users(id),updated_by uuid references auth.users(id)
);
create table public.site_settings (id uuid primary key default gen_random_uuid(),key text unique not null check(key in ('header','footer')),value jsonb not null default '{}'::jsonb,status text not null default 'published' check(status in ('draft','published')),updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create table public.theme_settings (id uuid primary key default gen_random_uuid(),name text not null default 'original',theme_key text not null check(theme_key in ('original','white','soft-blue','soft-lavender','warm-beige')),is_active boolean not null default true,tokens jsonb not null default '{}'::jsonb,updated_at timestamptz not null default now(),updated_by uuid references auth.users(id));
create unique index one_active_theme_idx on public.theme_settings((is_active)) where is_active;
create table public.content_revisions (id uuid primary key default gen_random_uuid(),entity_type text not null,entity_id uuid not null,action text not null check(action in ('create','update','publish','hide','delete')),previous_data jsonb,new_data jsonb,changed_by uuid references auth.users(id),changed_at timestamptz not null default now());
create index categories_sort_order_idx on public.categories(sort_order); create index content_category_idx on public.content_items(category_id); create index content_status_idx on public.content_items(status); create index media_created_at_idx on public.media(created_at desc); create index site_sections_page_sort_idx on public.site_sections(page_key,sort_order) where deleted_at is null; create index site_items_section_sort_idx on public.site_items(section_id,sort_order) where deleted_at is null; create index content_revisions_entity_idx on public.content_revisions(entity_type,entity_id,changed_at desc);
create trigger profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at(); create trigger categories_updated_at before update on public.categories for each row execute procedure public.set_updated_at(); create trigger content_updated_at before update on public.content_items for each row execute procedure public.set_updated_at(); create trigger site_sections_updated_at before update on public.site_sections for each row execute procedure public.set_updated_at(); create trigger site_items_updated_at before update on public.site_items for each row execute procedure public.set_updated_at(); create trigger site_settings_updated_at before update on public.site_settings for each row execute procedure public.set_updated_at(); create trigger theme_settings_updated_at before update on public.theme_settings for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security; alter table public.admins enable row level security; alter table public.categories enable row level security; alter table public.content_items enable row level security; alter table public.media enable row level security; alter table public.site_sections enable row level security; alter table public.site_items enable row level security; alter table public.site_settings enable row level security; alter table public.theme_settings enable row level security; alter table public.content_revisions enable row level security;
create policy "profiles own read" on public.profiles for select to authenticated using(id=auth.uid() or public.is_admin()); create policy "profiles own update" on public.profiles for update to authenticated using(id=auth.uid() or public.is_admin()) with check(id=auth.uid() or public.is_admin());
create policy "admins admin read" on public.admins for select to authenticated using(public.is_admin()); create policy "admins admin insert" on public.admins for insert to authenticated with check(public.is_admin()); create policy "admins admin delete" on public.admins for delete to authenticated using(public.is_admin() and (select count(*) from public.admins)>1);
create policy "categories public visible" on public.categories for select using(is_visible or public.is_admin()); create policy "categories admin write" on public.categories for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "content public published" on public.content_items for select using(status='published' or public.is_admin()); create policy "content admin write" on public.content_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "media admin read" on public.media for select to authenticated using(public.is_admin()); create policy "media admin write" on public.media for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "sections public published" on public.site_sections for select using((status='published' and is_visible and deleted_at is null) or public.is_admin()); create policy "sections admin write" on public.site_sections for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "items public published" on public.site_items for select using((status='published' and is_visible and deleted_at is null) or public.is_admin()); create policy "items admin write" on public.site_items for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "settings public published" on public.site_settings for select using(status='published' or public.is_admin()); create policy "settings admin write" on public.site_settings for all to authenticated using(public.is_admin()) with check(public.is_admin());
create policy "theme public active" on public.theme_settings for select using(is_active or public.is_admin()); create policy "theme admin write" on public.theme_settings for all to authenticated using(public.is_admin()) with check(public.is_admin()); create policy "revisions admin read" on public.content_revisions for select to authenticated using(public.is_admin()); create policy "revisions admin insert" on public.content_revisions for insert to authenticated with check(public.is_admin());

-- RLS decides which rows are available; these grants allow the Supabase API roles
-- to reach the tables in the first place.  They are essential after `drop schema
-- public cascade`, which removes Supabase's default table grants.
grant usage on schema public to anon, authenticated;
grant select on public.categories, public.content_items, public.site_sections, public.site_items, public.site_settings, public.theme_settings to anon, authenticated;
grant select, insert, update, delete on public.profiles, public.admins, public.categories, public.content_items, public.media, public.site_sections, public.site_items, public.site_settings, public.theme_settings, public.content_revisions to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('site-media','site-media',true,26214400,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "site media admin select" on storage.objects for select to authenticated using(bucket_id='site-media' and public.is_admin()); create policy "site media admin insert" on storage.objects for insert to authenticated with check(bucket_id='site-media' and public.is_admin()); create policy "site media admin delete" on storage.objects for delete to authenticated using(bucket_id='site-media' and public.is_admin());

insert into public.profiles(id,email,full_name,avatar_url) select id,coalesce(email,''),coalesce(raw_user_meta_data->>'full_name',raw_user_meta_data->>'name'),coalesce(raw_user_meta_data->>'avatar_url',raw_user_meta_data->>'picture') from auth.users on conflict(id) do nothing;
insert into public.categories(name_he,name_ar,slug,sort_order,is_visible) values('אותיות בקבוצות','الحروف ضمن مجموعات','letters',1,true),('דפי עבודה','أوراق عمل','worksheets',2,true),('חומרי העשרה','مواد إثرائية','resources',3,true),('טיפ השבוע','نصيحة الأسبوع','weekly-tip',4,true);
insert into public.theme_settings(name,theme_key,is_active) values('Original','original',true);
insert into public.site_settings(key,value) values('header','{"brand_he":"קדם־כתיבה בערבית","brand_ar":"الكتابة التمهيدية بالعربية"}'),('footer','{"text_he":"פרויקט גמר | התואר השני בריפוי בעיסוק | אוניברסיטת תל־אביב","text_ar":"مشروع تخرج | الماجستير في العلاج الوظيفي | جامعة تل أبيب"}');
insert into public.site_sections(key,page_key,section_type,title_he,title_ar,subtitle_he,subtitle_ar,sort_order,settings) values
('home.hero','home','hero','קדם־כתיבה וכתיבת אותיות בערבית','الكتابة التمهيدية وكتابة الحروف العربية','כלים מקצועיים לקידום מיומנויות קדם־כתיבה וכתיבת אותיות בערבית בגיל הרך','أدوات مهنية لتنمية مهارات ما قبل الكتابة وكتابة الحروف العربية في الطفولة المبكرة',1,'{"cta_href":"#guide","cta_label_he":"התחילו כאן","cta_label_ar":"ابدأوا من هنا","visual_mode":"letters"}'),('home.features','home','feature_grid','המדריך המקצועי','الدليل المهني',null,null,2,'{}'),('home.explore','home','explore','שלוש דרכים להתחיל','ثلاث طرق للبدء','מבט מקצועי שמחבר בין האות, הילד והפעילות.','منظور مهني يربط بين الحرف والطفل والنشاط.',3,'{}'),
('letters.content','letters','content','אותיות בקבוצות','الحروف ضمن مجموعات','ארגון ראשוני של אותיות לפי מאפיינים חזותיים, מבניים ומוטוריים.','تنظيم أولي للحروف وفق خصائص بصرية وبنيوية وحركية.',1,'{}'),('worksheets.content','worksheets','content','דפי עבודה','أوراق عمل','מאגר דפי תרגול מדורגים.','مجموعة أوراق تدريب متدرجة.',1,'{}'),('resources.content','resources','content','חומרי העשרה','مواد إثرائية','כלים וחומרים לצוותים מקצועיים.','أدوات ومواد للفرق المهنية.',1,'{}'),('weekly-tip.content','weekly-tip','tip','טיפ השבוע','نصيحة الأسبوع','נקודת מבט מקצועית קצרה.','وجهة نظر مهنية موجزة.',1,'{}'),('project.content','project','content','על הפרויקט','عن المشروع','המיזם מנגיש ידע וכלים מקצועיים.','المشروع يتيح المعرفة والأدوات المهنية.',1,'{}'),('about.content','about','author','אודותיי','من أنا','היכרות מקצועית עם יוזמת המדריך.','تعارف مهني مع صاحبة الدليل.',1,'{}'),('skills.content','skills','content','מיומנויות','المهارات','מיומנויות התומכות בהתפתחות הכתיבה.','مهارات تدعم تطور الكتابة.',1,'{}'),('strategies.content','strategies','content','אסטרטגיות','استراتيجيات','כיוונים להתערבות ולתרגול מדורג.','اتجاهات للتدخل والتدريب المتدرج.',1,'{}');
insert into public.site_items(section_id,item_type,title_he,title_ar,description_he,description_ar,cta_label_he,cta_label_ar,cta_href,icon_key,variant,sort_order)
select s.id,'feature_card',v.he,v.ar,v.desc_he,v.desc_ar,v.cta_he,v.cta_ar,v.href,v.icon,v.variant,v.ord from public.site_sections s join (values
('home.features','אותיות בקבוצות','الحروف ضمن مجموعات','הכירו את צורת האות, מופעיה והאתגרים האפשריים.','تعرّفوا إلى شكل الحرف وظهوره والتحديات المحتملة.','לצפייה','عرض','/letters','pencil','sage',1),('home.features','דפי עבודה','أوراق عمل','מאגר תרגול מדורג להרחבה.','مجموعة تمارين متدرجة قابلة للتوسيع.','לצפייה','عرض','/worksheets','book','peach',2),('home.features','חומרי העשרה','مواد إثرائية','כלים וחומרים לצוותים מקצועיים.','أدوات ومواد للفرق المهنية.','לצפייה','عرض','/resources','brain','lavender',3),('home.features','טיפ השבוע','نصيحة الأسبوع','נקודת מבט מקצועית קצרה.','وجهة نظر مهنية موجزة.','לצפייה','عرض','/weekly-tip','leaf','yellow',4),
('letters.content','מפת אותיות','خريطة الحروف','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',1),('letters.content','קבוצות חזותיות','مجموعات بصرية','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',2),('letters.content','ניתוח אות','تحليل الحرف','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',3),
('worksheets.content','קווים קדם־כתיבתיים','خطوط تمهيدية للكتابة','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',1),('worksheets.content','תרגול נקודות','تمارين النقاط','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',2),('worksheets.content','עקיבה אחר אות','تتبع الحرف','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',3),('worksheets.content','העתקה מדורגת','نسخ متدرج','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',4),
('resources.content','כלים להדרכה','أدوات للإرشاد','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',1),('resources.content','חומרים לצוותים','مواد للفرق','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',2),('resources.content','מקורות מקצועיים','مصادر مهنية','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',3),
('project.content','מטרת המיזם','هدف المشروع','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',1),('project.content','המסגרת האקדמית','الإطار الأكاديمي','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',2),('project.content','המשך הדרך','الخطوات القادمة','המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.',null,null,null,null,'default',3)
) as v(section_key,he,ar,desc_he,desc_ar,cta_he,cta_ar,href,icon,variant,ord) on s.key=v.section_key;
insert into public.site_items(section_id,item_type,title_he,title_ar,description_he,description_ar,variant,sort_order)
select s.id,'feature_card',v.he,v.ar,'המידע המקצועי יתווסף ויעודכן על ידי צוות האתר.','ستتم إضافة المعلومات المهنية وتحديثها من قبل فريق الموقع.','default',v.ord from public.site_sections s join (values
('weekly-tip.content','טיפ מקצועי שבועי','نصيحة مهنية أسبوعية',1),('about.content','היכרות מקצועית','تعارف مهني',1),('about.content','הגישה המקצועית','المنهج المهني',2),('skills.content','מיומנויות מוטוריות','مهارات حركية',1),('skills.content','תכנון תנועה','تخطيط الحركة',2),('skills.content','מוכנות לכתיבה','الاستعداد للكتابة',3),('strategies.content','התאמת פעילות','ملاءمة النشاط',1),('strategies.content','תרגול מדורג','تدريب متدرج',2),('strategies.content','תצפית ומשוב','ملاحظة وتغذية راجعة',3)
) as v(section_key,he,ar,ord) on s.key=v.section_key;
-- Bootstrap after the user signs in once:
-- insert into public.admins(user_id) select id from auth.users where email='fuadnasiraldin@gmail.com';
